### ISSUE TITLE
Что за слово Pathes?

### ISSUE THREAD

**Issue by TheTitanrain** [alexander-nesterov/zabbix_template_WSUS#3]
То ли пути, то ли патчи...

**Comment by 0x12ee705** [comment]
Поменяйте на свое слово, если не нравится

**Comment by TheTitanrain** [comment]
Не, ну это набор букв или оно что-то значит?

**Comment by 0x12ee705** [comment]
этот набор букв значит что я пропустил букву 'c' (patches), а по сути это на работу никак не влияет, назовите как Вам хочется.
